name: deploy new version to render

on:
  workflow_call:

jobs:
  trigger-deployment:
    runs-on: ubuntu-20.04
    env:
      render_hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
      test_hook: https://www.google.com/
      dummy_render_hook: ${{ secrets.DUMMY_RENDER_DEPLOY_HOOK }}
    steps:
      - name: echo dummy hook
        run: echo dummy hook "$dummy_render_hook"
      - name: trigger deployment
        run: curl "$dummy_render_hook"
        # run: curl "$test_hook"
