name: frontend ci pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        working-directory: ./frontend
      - uses: ./.github/actions/npm-install
      - name: build application
        run: npm run build
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        working-directory: ./frontend
      - uses: ./.github/actions/node-install
      - name: run eslint
        run: npm run lint
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        working-directory: ./frontend
      - uses: ./.github/actions/node-install
      - name: run unit tests
        run: npm run test
