name: main ci pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  frontend-ci-jobs:
    uses: ./.github/workflows/frontend-ci-jobs.yml
  backend-ci-jobs:
    uses: ./.github/workflows/backend-ci-jobs.yml
