name: main ci pipeline

on:
  push:
    branches:
      - develop
      - master


  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  frontend-ci-jobs:
    uses: ./.github/workflows/frontend-ci-jobs.yml
  backend-ci-jobs:
    uses: ./.github/workflows/backend-ci-jobs.yml
  playwright-e2e-tests:
    needs:
      - frontend-ci-jobs
      - backend-ci-jobs
    uses: ./.github/workflows/playwright-e2e-tests.yml
  deploy-new-version-to-staging-environment:
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs:
      - frontend-ci-jobs
      - backend-ci-jobs
      - playwright-e2e-tests
    uses: ./.github/workflows/deploy-jobs.yml
    secrets:
      render_hook: ${{ secrets.STAGING_RENDER_DEPLOY_HOOK }}
  deploy-new-version-to-production:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - frontend-ci-jobs
      - backend-ci-jobs
      - playwright-e2e-tests
    uses: ./.github/workflows/deploy-jobs.yml
    secrets:
      render_hook: ${{ secrets.PRODUCTION_RENDER_DEPLOY_HOOK }}
