name: main ci pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  frontend-ci-jobs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/workflows/actions/frontend-ci-jobs
  backend-ci-jobs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/workflows/actions/backend-ci-jobs
