name: frontend ci pipeline

on:
  workflow_call:

jobs:
  build_frontend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - name: build frontend
        run: npm run build
